In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
df = pd.read_csv('BTC-USD.csv')

In [4]:
df

Date         Open         High          Low        Close  \
0    08-06-2023  26347.65430  26797.51367  26246.66406  26508.21680   
1    09-06-2023  26505.92383  26770.28906  26339.31445  26480.37500   
2    10-06-2023  26481.76172  26531.04492  25501.83594  25851.24023   
3    11-06-2023  25854.03125  26203.43945  25668.98633  25940.16797   
4    12-06-2023  25934.28516  26087.91992  25675.19727  25902.50000   
..          ...          ...          ...          ...          ...   
362  04-06-2024  68804.57031  71047.40625  68564.64063  70567.76563   
363  05-06-2024  70568.35156  71735.41406  70390.71094  71082.82031   
364  06-06-2024  71082.84375  71625.73438  70119.12500  70757.16406   
365  07-06-2024  70759.18750  71907.85156  68507.25781  69342.58594   
366  08-06-2024  69324.17969  69533.32031  69210.74219  69463.69531   

       Adj Close        Volume  
0    26508.21680  1.190482e+10  
1    26480.37500  1.101555e+10  
2    25851.24023  1.987293e+10  
3    25940.16797  1.073261e+10  
4    25902.50000  1.167789e+10  
..           ...           ...  
362  70567.76563  3.314970e+10  
363  71082.82031  3.281077e+10  
364  70757.16406  2.522315e+10  
365  69342.58594  3.618838e+10  
366  69463.69531  2.692020e+10  

[367 rows x 7 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       367 non-null    object 
 1   Open       367 non-null    float64
 2   High       367 non-null    float64
 3   Low        367 non-null    float64
 4   Close      367 non-null    float64
 5   Adj Close  367 non-null    float64
 6   Volume     367 non-null    float64
dtypes: float64(6), object(1)
memory usage: 20.2+ KB


In [6]:
#Feature Engineering

#Finding the Relative Strength Index

delta = df['Close'].diff(1)
delta.dropna(inplace = True)
positive = delta.copy()
negative = delta.copy()

positive[ positive < 0] = 0
negative[ negative > 0] = 0

days = 14

average_gain = positive.rolling(window = days).mean()
average_loss = abs(negative.rolling(window = days).mean())

relative_strength = average_gain/average_loss

RSI = 100.0 - (100.0/ (1.0 + relative_strength))

RSI

1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
         ...    
362    51.839588
363    58.735150
364    63.653717
365    53.653915
366    50.936849
Name: Close, Length: 366, dtype: float64

In [7]:
df['RSI'] = RSI
df['RSI'] = df['RSI'].fillna(0)
df

Date         Open         High          Low        Close  \
0    08-06-2023  26347.65430  26797.51367  26246.66406  26508.21680   
1    09-06-2023  26505.92383  26770.28906  26339.31445  26480.37500   
2    10-06-2023  26481.76172  26531.04492  25501.83594  25851.24023   
3    11-06-2023  25854.03125  26203.43945  25668.98633  25940.16797   
4    12-06-2023  25934.28516  26087.91992  25675.19727  25902.50000   
..          ...          ...          ...          ...          ...   
362  04-06-2024  68804.57031  71047.40625  68564.64063  70567.76563   
363  05-06-2024  70568.35156  71735.41406  70390.71094  71082.82031   
364  06-06-2024  71082.84375  71625.73438  70119.12500  70757.16406   
365  07-06-2024  70759.18750  71907.85156  68507.25781  69342.58594   
366  08-06-2024  69324.17969  69533.32031  69210.74219  69463.69531   

       Adj Close        Volume        RSI  
0    26508.21680  1.190482e+10   0.000000  
1    26480.37500  1.101555e+10   0.000000  
2    25851.24023  1.987293e+10   0.000000  
3    25940.16797  1.073261e+10   0.000000  
4    25902.50000  1.167789e+10   0.000000  
..           ...           ...        ...  
362  70567.76563  3.314970e+10  51.839588  
363  71082.82031  3.281077e+10  58.735150  
364  70757.16406  2.522315e+10  63.653717  
365  69342.58594  3.618838e+10  53.653915  
366  69463.69531  2.692020e+10  50.936849  

[367 rows x 8 columns]

In [8]:
#Finding Simple Moving Average

period = 5
SMA = df['Close'].rolling(window= period).mean()

SMA

0               NaN
1               NaN
2               NaN
3               NaN
4      26136.500000
           ...     
362    68464.500000
363    69182.781250
364    69792.826562
365    70111.023438
366    70242.806250
Name: Close, Length: 367, dtype: float64

In [9]:
df['SMA'] = SMA
df['SMA'] = df['SMA'].fillna(0)
df

Date         Open         High          Low        Close  \
0    08-06-2023  26347.65430  26797.51367  26246.66406  26508.21680   
1    09-06-2023  26505.92383  26770.28906  26339.31445  26480.37500   
2    10-06-2023  26481.76172  26531.04492  25501.83594  25851.24023   
3    11-06-2023  25854.03125  26203.43945  25668.98633  25940.16797   
4    12-06-2023  25934.28516  26087.91992  25675.19727  25902.50000   
..          ...          ...          ...          ...          ...   
362  04-06-2024  68804.57031  71047.40625  68564.64063  70567.76563   
363  05-06-2024  70568.35156  71735.41406  70390.71094  71082.82031   
364  06-06-2024  71082.84375  71625.73438  70119.12500  70757.16406   
365  07-06-2024  70759.18750  71907.85156  68507.25781  69342.58594   
366  08-06-2024  69324.17969  69533.32031  69210.74219  69463.69531   

       Adj Close        Volume        RSI           SMA  
0    26508.21680  1.190482e+10   0.000000      0.000000  
1    26480.37500  1.101555e+10   0.000000      0.000000  
2    25851.24023  1.987293e+10   0.000000      0.000000  
3    25940.16797  1.073261e+10   0.000000      0.000000  
4    25902.50000  1.167789e+10   0.000000  26136.500000  
..           ...           ...        ...           ...  
362  70567.76563  3.314970e+10  51.839588  68464.500000  
363  71082.82031  3.281077e+10  58.735150  69182.781250  
364  70757.16406  2.522315e+10  63.653717  69792.826562  
365  69342.58594  3.618838e+10  53.653915  70111.023438  
366  69463.69531  2.692020e+10  50.936849  70242.806250  

[367 rows x 9 columns]

In [10]:
#Finding Exponential Moving Average

EMA = df['Close'].ewm(span = 5, min_periods = 0, adjust = False).mean()
EMA

0      26508.216800
1      26498.936200
2      26283.037543
3      26168.747686
4      26079.998457
           ...     
362    68980.494101
363    69681.269504
364    70039.901023
365    69807.462662
366    69692.873545
Name: Close, Length: 367, dtype: float64

In [11]:
df['EMA'] = EMA
df

Date         Open         High          Low        Close  \
0    08-06-2023  26347.65430  26797.51367  26246.66406  26508.21680   
1    09-06-2023  26505.92383  26770.28906  26339.31445  26480.37500   
2    10-06-2023  26481.76172  26531.04492  25501.83594  25851.24023   
3    11-06-2023  25854.03125  26203.43945  25668.98633  25940.16797   
4    12-06-2023  25934.28516  26087.91992  25675.19727  25902.50000   
..          ...          ...          ...          ...          ...   
362  04-06-2024  68804.57031  71047.40625  68564.64063  70567.76563   
363  05-06-2024  70568.35156  71735.41406  70390.71094  71082.82031   
364  06-06-2024  71082.84375  71625.73438  70119.12500  70757.16406   
365  07-06-2024  70759.18750  71907.85156  68507.25781  69342.58594   
366  08-06-2024  69324.17969  69533.32031  69210.74219  69463.69531   

       Adj Close        Volume        RSI           SMA           EMA  
0    26508.21680  1.190482e+10   0.000000      0.000000  26508.216800  
1    26480.37500  1.101555e+10   0.000000      0.000000  26498.936200  
2    25851.24023  1.987293e+10   0.000000      0.000000  26283.037543  
3    25940.16797  1.073261e+10   0.000000      0.000000  26168.747686  
4    25902.50000  1.167789e+10   0.000000  26136.500000  26079.998457  
..           ...           ...        ...           ...           ...  
362  70567.76563  3.314970e+10  51.839588  68464.500000  68980.494101  
363  71082.82031  3.281077e+10  58.735150  69182.781250  69681.269504  
364  70757.16406  2.522315e+10  63.653717  69792.826562  70039.901023  
365  69342.58594  3.618838e+10  53.653915  70111.023438  69807.462662  
366  69463.69531  2.692020e+10  50.936849  70242.806250  69692.873545  

[367 rows x 10 columns]

In [12]:
df = df[['Date','Close','RSI', 'SMA', 'EMA']]
df

Date        Close        RSI           SMA           EMA
0    08-06-2023  26508.21680   0.000000      0.000000  26508.216800
1    09-06-2023  26480.37500   0.000000      0.000000  26498.936200
2    10-06-2023  25851.24023   0.000000      0.000000  26283.037543
3    11-06-2023  25940.16797   0.000000      0.000000  26168.747686
4    12-06-2023  25902.50000   0.000000  26136.500000  26079.998457
..          ...          ...        ...           ...           ...
362  04-06-2024  70567.76563  51.839588  68464.500000  68980.494101
363  05-06-2024  71082.82031  58.735150  69182.781250  69681.269504
364  06-06-2024  70757.16406  63.653717  69792.826562  70039.901023
365  07-06-2024  69342.58594  53.653915  70111.023438  69807.462662
366  08-06-2024  69463.69531  50.936849  70242.806250  69692.873545

[367 rows x 5 columns]

In [64]:
from sklearn.model_selection import train_test_split


In [65]:
#Splitting the dataset into training and testing dataset

X = df[['RSI', "SMA", "EMA"]]
y = df['Close']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)
print(X_train)

           RSI           SMA           EMA
63   54.439288  29395.802346  29422.500533
241  56.338913  42884.014064  42785.805284
306  47.931312  69373.335942  69457.482293
317  41.975580  63487.864064  64160.680754
245  82.920868  43589.342190  43996.649282
..         ...           ...           ...
323  41.273648  65151.775782  64545.888768
192  55.392152  42289.850782  42029.856543
117  53.005535  27364.830080  27343.445873
47   34.973361  29633.878516  29542.077807
172  53.463998  37507.996874  37387.434614

[293 rows x 3 columns]


In [66]:
X_train = np.array([X_train]).reshape(-1,3)
X_train


array([[5.44392884e+01, 2.93958023e+04, 2.94225005e+04],
       [5.63389126e+01, 4.28840141e+04, 4.27858053e+04],
       [4.79313117e+01, 6.93733359e+04, 6.94574823e+04],
       [4.19755800e+01, 6.34878641e+04, 6.41606808e+04],
       [8.29208680e+01, 4.35893422e+04, 4.39966493e+04],
       [3.51501522e+01, 6.09937305e+04, 6.05476952e+04],
       [8.24578708e+01, 3.03942309e+04, 3.02941580e+04],
       [8.92402396e+01, 3.42393734e+04, 3.41240964e+04],
       [9.24809039e+01, 3.46470906e+04, 3.46826344e+04],
       [1.84940109e+01, 2.94109016e+04, 2.93900361e+04],
       [5.87351503e+01, 6.91827812e+04, 6.96812695e+04],
       [5.24648784e+01, 6.14978242e+04, 6.18356551e+04],
       [4.40549906e+01, 6.97229469e+04, 6.90051056e+04],
       [5.08964018e+01, 4.28607312e+04, 4.27213467e+04],
       [8.02235849e+01, 6.22682047e+04, 6.13675131e+04],
       [6.36597371e+01, 7.14978125e+04, 7.05519088e+04],
       [4.33999281e+01, 6.46317602e+04, 6.50071789e+04],
       [8.05974877e+01, 3.03936

In [67]:
from sklearn.preprocessing import MinMaxScaler
scaler_X = MinMaxScaler(feature_range=(0,1))
X_train = scaler_X.fit_transform(X_train)
X_train

array([[0.56553777, 0.41114268, 0.082805  ],
       [0.58527185, 0.59979477, 0.37670751],
       [0.49793023, 0.97028613, 0.96330439],
       [0.43605963, 0.88796932, 0.8468105 ],
       [0.86141616, 0.6096598 , 0.40333791],
       [0.36515427, 0.85308527, 0.76734921],
       [0.85660636, 0.42510714, 0.10197558],
       [0.9270644 , 0.47888701, 0.18620838],
       [0.96072976, 0.48458952, 0.19849244],
       [0.19212341, 0.41135387, 0.082091  ],
       [0.61016496, 0.96762095, 0.9682262 ],
       [0.54502679, 0.86013574, 0.79567563],
       [0.4576614 , 0.97517595, 0.95335515],
       [0.5287328 , 0.59946913, 0.37528986],
       [0.83339567, 0.87091063, 0.78537967],
       [0.66132359, 1.        , 0.98737439],
       [0.45085635, 0.90396836, 0.86542775],
       [0.83727993, 0.42509872, 0.10331786],
       [0.66599781, 0.60322627, 0.39604146],
       [0.23441379, 0.57115788, 0.32990932],
       [0.65649291, 0.61046862, 0.39099412],
       [0.74225709, 0.4102039 , 0.08254989],
       [0.

In [68]:
X_test = np.array([X_test]).reshape(-1,3)
X_test = scaler_X.transform(X_test)
X_test

array([[6.16766309e-01, 3.75520880e-01, 2.31998801e-02],
       [8.28898121e-01, 7.25422806e-01, 5.71775170e-01],
       [5.08513408e-01, 4.18113562e-01, 9.46411860e-02],
       [7.51214367e-01, 4.29725374e-01, 1.11706024e-01],
       [1.50573586e-01, 3.65878267e-01, 1.25659081e-02],
       [7.06027469e-01, 9.42548625e-01, 9.25019897e-01],
       [4.40304909e-01, 3.61364902e-01, 4.66683388e-03],
       [4.07811450e-01, 9.43817851e-01, 9.04074626e-01],
       [6.24466008e-01, 6.01655033e-01, 3.77772976e-01],
       [0.00000000e+00, 3.60115388e-01, 1.50077500e-03],
       [6.85745462e-01, 3.86368934e-01, 4.33413558e-02],
       [9.44227002e-01, 4.74299913e-01, 1.70393530e-01],
       [7.61756752e-01, 7.26913607e-01, 5.90896126e-01],
       [5.49135251e-01, 9.26128422e-01, 9.03746695e-01],
       [5.87811929e-01, 9.67920249e-01, 9.41741448e-01],
       [5.33622243e-01, 6.10979772e-01, 3.95825590e-01],
       [5.09407082e-01, 9.71725162e-01, 9.59440784e-01],
       [6.08255064e-01, 3.70582

In [69]:
y_train = np.array(y_train).reshape(-1,1)
scaler_Y = MinMaxScaler(feature_range=(0,1))
y_train = scaler_Y.fit_transform(y_train)
y_train

array([[0.08904136],
       [0.36353548],
       [0.91768751],
       [0.83119959],
       [0.42025369],
       [0.70868489],
       [0.11023798],
       [0.19489867],
       [0.21440773],
       [0.08447337],
       [0.95825033],
       [0.75938006],
       [0.87713838],
       [0.35343174],
       [0.79307275],
       [0.9232124 ],
       [0.81174588],
       [0.11090367],
       [0.41308358],
       [0.30639894],
       [0.38502005],
       [0.10081713],
       [0.04941755],
       [0.08598053],
       [0.09432836],
       [0.06604295],
       [0.92302003],
       [0.236634  ],
       [0.92825262],
       [0.26189212],
       [0.11096648],
       [0.44251998],
       [0.19835057],
       [0.82978482],
       [0.3521002 ],
       [0.36916113],
       [0.0427468 ],
       [0.88511458],
       [0.38765778],
       [0.88449899],
       [0.7693352 ],
       [0.35094212],
       [0.85178293],
       [0.20631316],
       [0.34339444],
       [0.01968864],
       [0.02749786],
       [0.218

In [70]:
y_test = np.array(y_test).reshape(-1,1)
y_test = scaler_Y.transform(y_test)
y_test

array([[ 2.95678016e-02],
       [ 5.45531240e-01],
       [ 1.02708637e-01],
       [ 1.17170881e-01],
       [ 1.84682398e-02],
       [ 9.65874878e-01],
       [ 1.23241153e-02],
       [ 8.46731139e-01],
       [ 3.76103652e-01],
       [-7.92526080e-04],
       [ 5.80946208e-02],
       [ 1.82533224e-01],
       [ 6.12671743e-01],
       [ 8.92117344e-01],
       [ 8.40642893e-01],
       [ 3.96847495e-01],
       [ 9.51199800e-01],
       [ 2.86208054e-02],
       [ 3.62041074e-01],
       [ 1.87684378e-01],
       [ 1.86284691e-01],
       [ 3.72561515e-01],
       [ 8.09501818e-02],
       [ 9.24288560e-01],
       [ 8.90530743e-01],
       [ 5.53002381e-01],
       [ 8.36315241e-02],
       [ 8.11097508e-01],
       [ 3.64990721e-02],
       [ 3.56368145e-01],
       [ 4.65009579e-02],
       [ 3.32136657e-02],
       [ 1.15457362e-01],
       [ 1.07117315e-01],
       [ 9.41777645e-02],
       [ 1.57775642e-02],
       [ 8.38450109e-02],
       [ 6.60607603e-02],
       [ 6.6

MACHINE LEARNING ALGORITHM IMPLEMENTATION

HYPERPARAMETER TUNING FOR RANDOM FOREST REGRESSOR

In [72]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

RFmodel = RandomForestRegressor()

n_estimators = [50,100,150,200,250,300]

param_grid = {'n_estimators' : n_estimators}

rf_grid = GridSearchCV(estimator = RFmodel, param_grid = param_grid, cv=5, verbose= 2, n_jobs = -1)
rf_grid.fit(X_train, y_train)

rf_grid.best_params_

Fitting 5 folds for each of 6 candidates, totalling 30 fits


c:\Users\nihar\B.Tech project\venv\lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


{'n_estimators': 50}

RANDOM FOREST REGRESSOR

In [74]:
RFmodel = RandomForestRegressor(n_estimators = 100)

RFmodel.fit(X_train, y_train)

predictions = RFmodel.predict(X_test)

predictions = scaler_Y.inverse_transform(predictions.reshape(-1,1))
print(predictions)



c:\Users\nihar\B.Tech project\venv\lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


[[26719.7043388]
 [52494.6323046]
 [30060.7876964]
 [31149.9280077]
 [26086.8652541]
 [68610.9623033]
 [26055.3118165]
 [65459.2579713]
 [42756.4057041]
 [25814.0296686]
 [27916.4645682]
 [34563.771953 ]
 [52625.6166406]
 [67601.4621102]
 [68260.2821095]
 [44013.0400802]
 [69513.9851594]
 [26453.9958022]
 [42946.371131 ]
 [34547.0276162]
 [34560.6061328]
 [43174.5802338]
 [28924.2690643]
 [68159.788751 ]
 [68568.9571096]
 [51849.192305 ]
 [29280.0332439]
 [63103.3130487]
 [26817.9556856]
 [42040.0560929]
 [27760.0576927]
 [26389.6636921]
 [29846.3267765]
 [30301.6771485]
 [29469.6153702]
 [26125.3009175]
 [29297.248419 ]
 [28356.5869537]
 [52670.0939459]
 [29407.8207609]
 [42513.9481252]
 [68786.1680477]
 [44169.4080496]
 [52361.8060921]
 [30584.5529081]
 [70380.6941404]
 [43930.3973066]
 [44869.5236345]
 [42747.3195704]
 [29409.7566205]
 [37609.8878882]
 [43657.370586 ]
 [42047.3741392]
 [37542.3472242]
 [26004.0592362]
 [29299.772853 ]
 [29317.3405279]
 [29737.8805655]
 [25955.238534

EXPORTING THE RANDOM FOREST MODEL 

In [25]:
import pickle
with open('RF_model.pkl', 'wb') as files:
    pickle.dump(RFmodel,files)

HYPERPARAMETER TUNING FOR GRADIENT BOOSTING REGRESSOR

In [26]:

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingRegressor

GBmodel = GradientBoostingRegressor()

n_estimators = [50,100,150,200]

learning_rate = [0.001,0.01,0.1]

param_grid_GB = {'n_estimators' : n_estimators,
                 'learning_rate' : learning_rate}

rf_grid_GB = GridSearchCV(estimator = GBmodel, param_grid = param_grid_GB, cv=5, verbose= 2, n_jobs = -1)
rf_grid_GB.fit(X_train, y_train)
rf_grid_GB.best_params_

Fitting 5 folds for each of 12 candidates, totalling 60 fits


c:\Users\nihar\B.Tech project\venv\lib\site-packages\sklearn\ensemble\_gb.py:668: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?


{'learning_rate': 0.1, 'n_estimators': 100}

GRADIENT BOOSTING REGRESSOR

In [75]:
GBModel = GradientBoostingRegressor(n_estimators= 100, learning_rate= 0.1)

GBModel.fit(X_train,y_train)

GBpredictions = GBModel.predict(X_test)

GBpredictions = scaler_Y.inverse_transform(GBpredictions.reshape(-1,1))
print(GBpredictions)


[[27026.73381736]
 [51941.2538512 ]
 [29943.802114  ]
 [31782.28947903]
 [25961.02356549]
 [69001.83155277]
 [25936.32547052]
 [65450.56693223]
 [42793.23821892]
 [26206.62707203]
 [27661.81931126]
 [34630.91790145]
 [52459.07126322]
 [67069.88445365]
 [68273.22337157]
 [43953.59069575]
 [69531.48059023]
 [26653.25769347]
 [43206.58715547]
 [34628.79682667]
 [34630.91790145]
 [43246.04861111]
 [29073.9875684 ]
 [67387.03111624]
 [68601.42300542]
 [51924.08339468]
 [29118.11830603]
 [63846.11965393]
 [26732.7770228 ]
 [42324.83887131]
 [27661.81931126]
 [26665.46809194]
 [29882.60006771]
 [30294.35091753]
 [29325.08424121]
 [26178.51556471]
 [29156.62852181]
 [28552.83071926]
 [52342.21924293]
 [29361.37505751]
 [42423.66184527]
 [69509.7437371 ]
 [43953.59069575]
 [51800.43356987]
 [30531.77030797]
 [70178.21284763]
 [43934.54127694]
 [44041.86886248]
 [42860.48514789]
 [29361.37505751]
 [37721.31846692]
 [43458.46305064]
 [42231.69881108]
 [37535.7037933 ]
 [26055.87522044]
 [29235.56

c:\Users\nihar\B.Tech project\venv\lib\site-packages\sklearn\ensemble\_gb.py:668: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?


EXPORTING THE GRADIENT BOOSTING MODEL

In [28]:
with open('GB_model.pkl', 'wb') as files:
    pickle.dump(GBModel,files)

DEEP LEARNING MODEL IMPLEMENTATION

In [80]:
#Reshaping Data for LSTM and GRU models
#data = data.reshape((data.shape[0], data.shape[1], 1))

X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_train



array([[[0.56553777],
        [0.41114268],
        [0.082805  ]],

       [[0.58527185],
        [0.59979477],
        [0.37670751]],

       [[0.49793023],
        [0.97028613],
        [0.96330439]],

       [[0.43605963],
        [0.88796932],
        [0.8468105 ]],

       [[0.86141616],
        [0.6096598 ],
        [0.40333791]],

       [[0.36515427],
        [0.85308527],
        [0.76734921]],

       [[0.85660636],
        [0.42510714],
        [0.10197558]],

       [[0.9270644 ],
        [0.47888701],
        [0.18620838]],

       [[0.96072976],
        [0.48458952],
        [0.19849244]],

       [[0.19212341],
        [0.41135387],
        [0.082091  ]],

       [[0.61016496],
        [0.96762095],
        [0.9682262 ]],

       [[0.54502679],
        [0.86013574],
        [0.79567563]],

       [[0.4576614 ],
        [0.97517595],
        [0.95335515]],

       [[0.5287328 ],
        [0.59946913],
        [0.37528986]],

       [[0.83339567],
        [0.87091063],
    

In [81]:
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))
X_test

array([[[6.16766309e-01],
        [3.75520880e-01],
        [2.31998801e-02]],

       [[8.28898121e-01],
        [7.25422806e-01],
        [5.71775170e-01]],

       [[5.08513408e-01],
        [4.18113562e-01],
        [9.46411860e-02]],

       [[7.51214367e-01],
        [4.29725374e-01],
        [1.11706024e-01]],

       [[1.50573586e-01],
        [3.65878267e-01],
        [1.25659081e-02]],

       [[7.06027469e-01],
        [9.42548625e-01],
        [9.25019897e-01]],

       [[4.40304909e-01],
        [3.61364902e-01],
        [4.66683388e-03]],

       [[4.07811450e-01],
        [9.43817851e-01],
        [9.04074626e-01]],

       [[6.24466008e-01],
        [6.01655033e-01],
        [3.77772976e-01]],

       [[0.00000000e+00],
        [3.60115388e-01],
        [1.50077500e-03]],

       [[6.85745462e-01],
        [3.86368934e-01],
        [4.33413558e-02]],

       [[9.44227002e-01],
        [4.74299913e-01],
        [1.70393530e-01]],

       [[7.61756752e-01],
        [7.269

LONG SHORT-TERM MEMORY MODEL

In [82]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM

#Creating a LSTM model

def create_model(units = 50):
    regressor = Sequential()

    regressor.add(LSTM(units=units, return_sequences = True, input_shape = (X_train.shape[1],X_train.shape[2])))
    regressor.add(Dropout(0.2))
    regressor.add(LSTM(units= units,return_sequences= True))
    regressor.add(Dropout(0.2))
    regressor.add(LSTM(units= units))
    regressor.add(Dropout(0.2))
    regressor.add(Dense(units=1))
    regressor.compile(optimizer='adam', loss='mean_squared_error')
    return regressor


HYPERPARAMETER TUNING FOR LSTM MODEL

In [83]:
from scikeras.wrappers import KerasRegressor

LSTM_model = KerasRegressor(build_fn= create_model,units=50)
batch_size = [16,32]
epochs = [50,100]
units = [50,100]

param_grid_LSTM = {'batch_size' : batch_size,
                 'epochs' : epochs,
                 'units': units}

rf_grid_LSTM = GridSearchCV(estimator = LSTM_model, param_grid = param_grid_LSTM, cv=5, verbose= 2, n_jobs = -1)
rf_grid_LSTM.fit(X_train, y_train)

rf_grid_LSTM.best_params_


Fitting 5 folds for each of 8 candidates, totalling 40 fits


c:\Users\nihar\B.Tech project\venv\lib\site-packages\joblib\externals\loky\process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
c:\Users\nihar\B.Tech project\venv\lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\nihar\B.Tech project\venv\lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 21s 17ms/step - loss: 0.2221
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0905
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0904
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0844
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0760
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0722
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0585
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0499
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0386
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0306
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0178
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0160
Epoch 13/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0077
Epoch 14/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0073
Epoch 15/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - l

{'batch_size': 32, 'epochs': 100, 'units': 100}

In [84]:
# Get the best parameters and re-create the model
best_params = rf_grid_LSTM.best_params_
best_units = best_params['units']
best_batch_size = best_params['batch_size']
best_epochs = best_params['epochs']

# Re-create the best model
best_model = create_model(best_units)

# Fit the best model on the training data
best_model.fit(X_train, y_train, batch_size=best_batch_size, epochs=best_epochs)

# Make predictions
LSTMpredictions = best_model.predict(X_test)

# Assuming `scaler` is the same MinMaxScaler used for scaling y_train and y_test
LSTMpredictions = scaler_Y.inverse_transform(LSTMpredictions.reshape(-1, 1))
print(LSTMpredictions)

# Save the best model properly using Keras' save function
best_model.save('LSTM_model.h5')


Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - loss: 0.2285
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0952
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0889
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0906
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0694
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0604
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0472
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0418
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0286
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0190
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0114
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0080
Epoch 13/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0084
Epoch 14/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071
Epoch 15/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.00

1/3 ━━━━━━━━━━━━━━━━━━━━ 1s 784ms/stepWARNING:tensorflow:6 out of the last 9 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x00000290540ABEB0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.


3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 374ms/step


[[27352.92 ]
 [52848.613]
 [30402.99 ]
 [31371.062]
 [26789.627]
 [68369.03 ]
 [26462.752]
 [66039.266]
 [43294.637]
 [26400.174]
 [28243.127]
 [34406.277]
 [53271.035]
 [66465.92 ]
 [68742.32 ]
 [43834.438]
 [68909.72 ]
 [27054.764]
 [43152.75 ]
 [34032.77 ]
 [34636.324]
 [43474.574]
 [29496.96 ]
 [67764.555]
 [68049.914]
 [52757.125]
 [29736.746]
 [62137.664]
 [27258.158]
 [42786.05 ]
 [28258.016]
 [27176.676]
 [29967.006]
 [30967.291]
 [29873.549]
 [26661.354]
 [29624.084]
 [28526.988]
 [54989.594]
 [29921.986]
 [42755.824]
 [68320.43 ]
 [44079.49 ]
 [52188.766]
 [30987.658]
 [69419.766]
 [44131.816]
 [45336.543]
 [43272.79 ]
 [29931.074]
 [38017.348]
 [43695.32 ]
 [42298.074]
 [37365.863]
 [26553.879]
 [29746.822]
 [29702.459]
 [29719.787]
 [26513.71 ]
 [26909.418]
 [63653.71 ]
 [65325.277]
 [26354.838]
 [26986.07 ]
 [62095.402]
 [64380.27 ]
 [29713.3  ]
 [28444.77 ]
 [44614.785]
 [36801.426]
 [27027.389]
 [37699.21 ]
 [27362.238]
 [69307.64 ]]


EXPORTING THE LSTM MODEL

GRATED RECURRENT UNIT MODEL IMPLEMENTATION

In [85]:
from tensorflow.keras.layers import GRU

#Creating a GRU model

def create_model_GRU(units):
    regressor = Sequential()

    regressor.add(GRU(units=units, return_sequences = True, input_shape = (X_train.shape[1],X_train.shape[2])))
    regressor.add(Dropout(0.2))
    regressor.add(GRU(units= units,return_sequences= True))
    regressor.add(Dropout(0.2))
    regressor.add(GRU(units= units))
    regressor.add(Dropout(0.2))
    regressor.add(Dense(units=1))
    regressor.compile(optimizer='adam', loss='mean_squared_error')
    return regressor

HYPERPARAMETER TUNING FOR GRU MODEL

In [86]:
GRU_model = KerasRegressor(build_fn= create_model_GRU, units=50)
batch_size = [16,32]
epochs = [50,100]       #32, 100, 100 best estimator
units = [50,100]

param_grid_GRU = {'batch_size' : batch_size,
                 'epochs' : epochs,
                 'units': units}

rf_grid_GRU = GridSearchCV(estimator = GRU_model, param_grid = param_grid_GRU, cv=5, verbose= 2, n_jobs = -1)
rf_grid_GRU.fit(X_train, y_train)

best_model = rf_grid_GRU.best_estimator_
best_model

Fitting 5 folds for each of 8 candidates, totalling 40 fits


c:\Users\nihar\B.Tech project\venv\lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\nihar\B.Tech project\venv\lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - loss: 0.1555
Epoch 2/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0699
Epoch 3/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0507
Epoch 4/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0309
Epoch 5/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0146
Epoch 6/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0104
Epoch 7/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0098
Epoch 8/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0083
Epoch 9/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 3s 148ms/step - loss: 0.0057
Epoch 10/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 0.0063
Epoch 11/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0046
Epoch 12/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0053
Epoch 13/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058
Epoch 14/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0062
Epoch 15/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - l

KerasRegressor(
	model=None
	build_fn=<function create_model_GRU at 0x00000290540ABB50>
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=None
	metrics=None
	batch_size=16
	validation_batch_size=None
	verbose=1
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=100
	units=50
)

In [87]:

# Get the best parameters and re-create the model
best_params = rf_grid_GRU.best_params_
best_units = best_params['units']
best_batch_size = best_params['batch_size']
best_epochs = best_params['epochs']

# Re-create the best model
best_model = create_model_GRU(best_units)

# Fit the best model on the training data
best_model.fit(X_train, y_train, batch_size=best_batch_size, epochs=best_epochs)

# Make predictions
GRUpredictions = best_model.predict(X_test)

# Assuming `scaler` is the same MinMaxScaler used for scaling y_train and y_test
GRUpredictions = scaler_Y.inverse_transform(GRUpredictions.reshape(-1, 1))
print(GRUpredictions)

# Save the best model properly using Keras' save function
best_model.save('GRU_model.h5')


Epoch 1/100


c:\Users\nihar\B.Tech project\venv\lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


19/19 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 0.1312
Epoch 2/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0674
Epoch 3/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0464
Epoch 4/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0240
Epoch 5/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0177
Epoch 6/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0120
Epoch 7/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0094
Epoch 8/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0066
Epoch 9/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0069
Epoch 10/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0047
Epoch 11/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056
Epoch 12/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0060
Epoch 13/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0067
Epoch 14/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0064
Epoch 15/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0037
Epoch 16/100
1

[[26974.701]
 [53341.15 ]
 [30063.777]
 [31340.914]
 [25997.965]
 [68706.96 ]
 [25818.615]
 [66207.21 ]
 [43557.88 ]
 [25720.535]
 [28026.143]
 [34397.055]
 [53925.734]
 [66906.98 ]
 [68815.19 ]
 [44086.676]
 [69079.04 ]
 [26665.766]
 [43302.668]
 [34069.082]
 [34636.145]
 [43613.508]
 [28897.45 ]
 [68122.86 ]
 [68408.64 ]
 [53164.29 ]
 [29217.45 ]
 [62841.617]
 [26877.158]
 [43092.79 ]
 [27972.928]
 [26875.082]
 [29952.982]
 [30592.238]
 [29473.809]
 [26011.98 ]
 [29254.193]
 [28220.041]
 [55692.145]
 [29567.326]
 [42989.652]
 [68772.41 ]
 [44309.93 ]
 [52675.336]
 [30956.389]
 [69696.78 ]
 [44439.664]
 [45778.383]
 [43547.887]
 [29560.312]
 [38122.594]
 [43766.19 ]
 [42584.176]
 [37463.188]
 [26015.082]
 [29221.734]
 [29125.113]
 [29631.271]
 [25958.805]
 [26165.562]
 [64085.766]
 [65707.92 ]
 [25672.795]
 [26641.291]
 [62488.5  ]
 [64896.36 ]
 [29204.594]
 [28290.969]
 [44732.656]
 [36743.438]
 [26313.527]
 [37787.434]
 [27002.293]
 [69385.65 ]]


EXPORTING THE GRU MODEL

In [38]:
df_1 = df
df_1

Date        Close        RSI           SMA           EMA
0    08-06-2023  26508.21680   0.000000      0.000000  26508.216800
1    09-06-2023  26480.37500   0.000000      0.000000  26498.936200
2    10-06-2023  25851.24023   0.000000      0.000000  26283.037543
3    11-06-2023  25940.16797   0.000000      0.000000  26168.747686
4    12-06-2023  25902.50000   0.000000  26136.500000  26079.998457
..          ...          ...        ...           ...           ...
362  04-06-2024  70567.76563  51.839588  68464.500000  68980.494101
363  05-06-2024  71082.82031  58.735150  69182.781250  69681.269504
364  06-06-2024  70757.16406  63.653717  69792.826562  70039.901023
365  07-06-2024  69342.58594  53.653915  70111.023438  69807.462662
366  08-06-2024  69463.69531  50.936849  70242.806250  69692.873545

[367 rows x 5 columns]

In [88]:
with open('scaler_X.pkl', 'wb') as files:
    pickle.dump(scaler_X,files)

In [89]:
with open('scaler_Y.pkl', 'wb') as files:
    pickle.dump(scaler_Y,files)